import { Nunito } from 'next/font/google';

import Footer from '@/components/Footer';
import Header from '@/components/Header';

import '../styles/global.scss';

const inter = Nunito({
  weight: ['900', '700', '600', '500', '400'],
  subsets: ['latin', 'cyrillic'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
