/* eslint-disable simple-import-sort/imports */
import { dir } from 'i18next';
import { Nunito } from 'next/font/google';

import Footer from '@/components/Footer';
import Header from '@/components/Header';
import '@/styles/global.scss';

import { languages } from '../i18n/settings';

const inter = Nunito({
  weight: ['900', '700', '600', '500', '400'],
  subsets: ['latin', 'cyrillic'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }));
}

export default function RootLayout({
  children,
  params: { lng },
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang={lng} dir={dir(lng)}>
      <body className={inter.className}>
        <div id="portal" />
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
